// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUTI6qRtrTcVCsawJGZkKAR0MKbrT0WS8',
    appId: '1:939391840043:android:e889d41e2c44af19449f6e',
    messagingSenderId: '939391840043',
    projectId: 'flutter-mxh',
    storageBucket: 'flutter-mxh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCculn7rgDwPj6WyUZtBVmH9lIyHRE3hYo',
    appId: '1:939391840043:ios:ede4952505e71a7d449f6e',
    messagingSenderId: '939391840043',
    projectId: 'flutter-mxh',
    storageBucket: 'flutter-mxh.firebasestorage.app',
    iosBundleId: 'com.example.mxh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCculn7rgDwPj6WyUZtBVmH9lIyHRE3hYo',
    appId: '1:939391840043:ios:ede4952505e71a7d449f6e',
    messagingSenderId: '939391840043',
    projectId: 'flutter-mxh',
    storageBucket: 'flutter-mxh.firebasestorage.app',
    iosBundleId: 'com.example.mxh',
  );
}

